services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: apinf
      POSTGRES_USER: apinf_user
      POSTGRES_PASSWORD: senha_segura
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data