version: '3.8'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: apinf
      POSTGRES_USER: apinf_user
      POSTGRES_PASSWORD: senha_segura
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data